# Generated by Django 5.0.3 on 2024-04-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_image',
            field=models.CharField(max_length=50),
        ),
    ]
